# Generated by Django 4.0.5 on 2022-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='default_odds',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='method',
            name='shiny_charm_odds',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
    ]
