# Generated by Django 4.0.5 on 2022-06-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_method_default_odds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunts', to='app_api.trainer'),
        ),
        migrations.AlterField(
            model_name='method',
            name='default_odds',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='method',
            name='shiny_charm_odds',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
