# Generated by Django 4.0.5 on 2022-06-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_alter_hunt_trainer_alter_method_default_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.trainer')),
            ],
        ),
    ]
